/**
 * The page's grain: one seamless turbulence tile, inline as a data URI.
 *
 * No binary asset and no image request: the tile is generated by the browser's
 * own filter, stays crisp at any zoom and any DPI, and weighs a couple of hundred
 * bytes of CSS. `stitchTiles` is what makes a 140px square repeat without a
 * visible seam, which is the whole trick with noise as a background.
 *
 * The alpha ramp in `feFuncA` is the strength control. Turbulence on its own is
 * hard black-and-white noise; scaling its alpha to 5.5% is what turns it into a
 * texture you read as paper rather than as dirt. Raise it for a coarser stock,
 * drop it for almost nothing.
 *
 * Painted once, behind everything, in `app/(marketing)/layout.tsx`, over the page
 * canvas (`bg-ds-bg`). The sections are transparent, so a single layer covers the
 * page from the hero to the footer and no section has to repeat it: that is also
 * why it sits on the shell rather than on a section.
 */
const NOISE_SVG = [
  "<svg xmlns='http://www.w3.org/2000/svg' width='140' height='140'>",
  "<filter id='n'>",
  "<feTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch'/>",
  "<feColorMatrix type='saturate' values='0'/>",
  "<feComponentTransfer><feFuncA type='linear' slope='0.055'/></feComponentTransfer>",
  '</filter>',
  "<rect width='140' height='140' filter='url(%23n)'/>",
  '</svg>',
].join('');

export const NOISE_BACKGROUND = `url("data:image/svg+xml,${NOISE_SVG.replaceAll(
  '<',
  '%3C',
)
  .replaceAll('>', '%3E')
  .replaceAll(' ', '%20')}")`;
