import type { IssueCard, LabelCard } from '@shipyard/shared';

const now = new Date().toISOString();

const labelBackend: LabelCard = {
  id: 'lbl_backend',
  workspaceId: 'ws_mock',
  name: 'backend',
  color: '#B45309',
};

const labelFrontend: LabelCard = {
  id: 'lbl_frontend',
  workspaceId: 'ws_mock',
  name: 'frontend',
  color: '#2563EB',
};

const labelBug: LabelCard = {
  id: 'lbl_bug',
  workspaceId: 'ws_mock',
  name: 'bug',
  color: '#B42318',
};

/**
 * Dummy issues that mirror the exact API shape (ListIssuesResponse.issues).
 * Mirrors the rows visible in shipyard.pen Screen / Issues - List (WDauM).
 * Grouped: Backlog 2, Todo 2, In Progress 2, Done 2.
 */
export const MOCK_ISSUES: IssueCard[] = [
  // Backlog — SHIP-122, SHIP-119
  {
    id: 'iss_122',
    workspaceId: 'ws_mock',
    seqNumber: 122,
    identifier: 'SHIP-122',
    title: 'Archived empty-state copy',
    status: 'BACKLOG',
    priority: 'MEDIUM',
    assignee: null,
    projectId: null,
    cycleId: null,
    dueDate: null,
    blocked: false,
    blockedReason: null,
    labels: [labelBackend],
    commentCount: 3,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'iss_119',
    workspaceId: 'ws_mock',
    seqNumber: 119,
    identifier: 'SHIP-119',
    title: 'Archive restore trip',
    status: 'BACKLOG',
    priority: 'NO_PRIORITY',
    assignee: null,
    projectId: null,
    cycleId: null,
    dueDate: '2025-01-05',
    blocked: false,
    blockedReason: null,
    labels: [],
    commentCount: 0,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  // Todo — SHIP-123, SHIP-125
  {
    id: 'iss_123',
    workspaceId: 'ws_mock',
    seqNumber: 123,
    identifier: 'SHIP-123',
    title: 'OAuth callback errors',
    status: 'TODO',
    priority: 'URGENT',
    assignee: {
      userId: 'usr_ar',
      name: 'Ana Ruiz',
      email: 'ana@harbor.test',
      image: null,
    },
    projectId: 'proj_1',
    cycleId: null,
    dueDate: '2025-12-10',
    blocked: true,
    blockedReason: 'Waiting on IdP fix',
    labels: [labelFrontend],
    commentCount: 5,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'iss_125',
    workspaceId: 'ws_mock',
    seqNumber: 125,
    identifier: 'SHIP-125',
    title: 'Mention suggestions',
    status: 'TODO',
    priority: 'LOW',
    assignee: {
      userId: 'usr_ck',
      name: 'Chen Kim',
      email: 'chen@harbor.test',
      image: null,
    },
    projectId: null,
    cycleId: null,
    dueDate: '2025-12-15',
    blocked: false,
    blockedReason: null,
    labels: [],
    commentCount: 1,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  // In Progress — SHIP-124, SHIP-130
  {
    id: 'iss_124',
    workspaceId: 'ws_mock',
    seqNumber: 124,
    identifier: 'SHIP-124',
    title: 'Fix login redirect after OAuth',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignee: {
      userId: 'usr_ym',
      name: 'Yonatane Mekete',
      email: 'yonatane@harbor.test',
      image: null,
    },
    projectId: 'proj_2',
    cycleId: null,
    dueDate: '2025-12-12',
    blocked: false,
    blockedReason: null,
    labels: [labelBug],
    commentCount: 2,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'iss_130',
    workspaceId: 'ws_mock',
    seqNumber: 130,
    identifier: 'SHIP-130',
    title: 'Real-time presence for issues',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assignee: {
      userId: 'usr_sp',
      name: 'Sam Park',
      email: 'sam@harbor.test',
      image: null,
    },
    projectId: 'proj_1',
    cycleId: null,
    dueDate: null,
    blocked: false,
    blockedReason: null,
    labels: [labelBackend, labelFrontend],
    commentCount: 4,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  // Done — SHIP-118, SHIP-117
  {
    id: 'iss_118',
    workspaceId: 'ws_mock',
    seqNumber: 118,
    identifier: 'SHIP-118',
    title: 'Design system tokens audit',
    status: 'DONE',
    priority: 'MEDIUM',
    assignee: {
      userId: 'usr_ym',
      name: 'Yonatane Mekete',
      email: 'yonatane@harbor.test',
      image: null,
    },
    projectId: null,
    cycleId: null,
    dueDate: '2025-11-20',
    blocked: false,
    blockedReason: null,
    labels: [],
    commentCount: 0,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'iss_117',
    workspaceId: 'ws_mock',
    seqNumber: 117,
    identifier: 'SHIP-117',
    title: 'Ship kanban board',
    status: 'DONE',
    priority: 'LOW',
    assignee: {
      userId: 'usr_ar',
      name: 'Ana Ruiz',
      email: 'ana@harbor.test',
      image: null,
    },
    projectId: 'proj_2',
    cycleId: null,
    dueDate: null,
    blocked: false,
    blockedReason: null,
    labels: [labelFrontend],
    commentCount: 6,
    archivedAt: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const MOCK_LIST_RESPONSE = {
  issues: MOCK_ISSUES,
};
